### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by chengjun** [chbrown/liwc-python#1]
It returns the keyerror when read the line `like	(02 134)125/464	(02 134)126	253	466`

    KeyError: '(02 134)125/464'

**Comment by chbrown** [comment]
What is "it"? I'm really quite terrible at reading minds (sorry!), so if you provide a traceback, that would help.

**Comment by chbrown** [comment]
Closing due to lack of details / inability to replicate.

**Comment by atishaycn** [comment]
parse, category_names = liwc.load_token_parser('LIWC2007_English100131.dic')

This returns a - key error '<of>131/125'
