### ISSUE TITLE
convert the text to lower case

### ISSUE THREAD

**Issue by mengyingzhou** [chbrown/liwc-python#11]
hi,
thank you for your awesome work.

this is not a bug, just a usage precautions.
When you using this package, you need to **convert the text to lower case** by manual.

for example:
the result of  ```parse('Our')``` is blank, but ```parse('our')``` works.

thx
Mengying

**Comment by chbrown** [comment]
Good point, thanks for the precaution! 😉

I wasn't doing that in my example 😞, much less indicating the importance of doing so.

Fixed in 60dbdc1 — improved documentation.
